/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type City = string;
export interface Dress {
  'id' : DressId,
  'status' : DressStatus,
  'rotationCity' : City,
  'originalPrice' : bigint,
  'priorityFees' : Array<bigint>,
  'color' : string,
  'size' : Size,
  'productLink' : [] | [string],
  'occasion' : Occasion,
  'brand' : string,
  'slotsFilled' : bigint,
  'initiatorId' : UserId,
  'groupSize' : bigint,
  'authenticityProof' : ExternalBlob,
  'photos' : Array<ExternalBlob>,
}
export type DressId = string;
export type DressStatus = { 'resale' : null } |
  { 'active' : null } |
  { 'cleaning' : null } |
  { 'complete' : null } |
  { 'forming' : null };
export type ExternalBlob = Uint8Array;
export interface FindDressParams {
  'city' : string,
  'size' : string,
  'priceRange' : string,
  'searchTerm' : string,
  'occasion' : string,
}
export interface Group {
  'id' : GroupId,
  'conditionPhotos' : Array<ExternalBlob>,
  'members' : Array<GroupMember>,
  'rotationSchedule' : Array<RotationSchedule>,
  'dressId' : DressId,
  'chatRoomId' : string,
  'currentHolder' : [] | [UserId],
  'currentStatus' : string,
  'handOverPhotos' : Array<ExternalBlob>,
}
export type GroupId = string;
export interface GroupMember {
  'slotFee' : bigint,
  'paymentStatus' : string,
  'userId' : UserId,
  'isConfirmed' : boolean,
  'shareAmount' : bigint,
  'slotNumber' : SlotNumber,
  'depositPaid' : boolean,
}
export type Occasion = { 'wedding' : null } |
  { 'casual' : null } |
  { 'party' : null } |
  { 'formal' : null };
export interface RotationSchedule {
  'status' : string,
  'endDate' : Time,
  'userId' : UserId,
  'startDate' : Time,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export type Size = { 'L' : null } |
  { 'M' : null } |
  { 'S' : null } |
  { 'XL' : null } |
  { 'XS' : null };
export type SlotNumber = bigint;
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfile {
  'principal' : Principal,
  'city' : City,
  'name' : string,
  'profilePhoto' : [] | [ExternalBlob],
  'trustScore' : number,
  'earnings' : bigint,
  'measurements' : { 'hip' : bigint, 'bust' : bigint, 'waist' : bigint },
  'depositBalance' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createGroupWithDress' : ActorMethod<[Group], string>,
  'getAllDresses' : ActorMethod<[], Array<Dress>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDress' : ActorMethod<[DressId], Dress>,
  'getFullGroupDetails' : ActorMethod<[GroupId], Group>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'postDressPhotos' : ActorMethod<[Array<ExternalBlob>, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDresses' : ActorMethod<[FindDressParams], Array<Dress>>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];