/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const GroupId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserId = IDL.Principal;
export const SlotNumber = IDL.Nat;
export const GroupMember = IDL.Record({
  'slotFee' : IDL.Nat,
  'paymentStatus' : IDL.Text,
  'userId' : UserId,
  'isConfirmed' : IDL.Bool,
  'shareAmount' : IDL.Nat,
  'slotNumber' : SlotNumber,
  'depositPaid' : IDL.Bool,
});
export const Time = IDL.Int;
export const RotationSchedule = IDL.Record({
  'status' : IDL.Text,
  'endDate' : Time,
  'userId' : UserId,
  'startDate' : Time,
});
export const DressId = IDL.Text;
export const Group = IDL.Record({
  'id' : GroupId,
  'conditionPhotos' : IDL.Vec(ExternalBlob),
  'members' : IDL.Vec(GroupMember),
  'rotationSchedule' : IDL.Vec(RotationSchedule),
  'dressId' : DressId,
  'chatRoomId' : IDL.Text,
  'currentHolder' : IDL.Opt(UserId),
  'currentStatus' : IDL.Text,
  'handOverPhotos' : IDL.Vec(ExternalBlob),
});
export const DressStatus = IDL.Variant({
  'resale' : IDL.Null,
  'active' : IDL.Null,
  'cleaning' : IDL.Null,
  'complete' : IDL.Null,
  'forming' : IDL.Null,
});
export const City = IDL.Text;
export const Size = IDL.Variant({
  'L' : IDL.Null,
  'M' : IDL.Null,
  'S' : IDL.Null,
  'XL' : IDL.Null,
  'XS' : IDL.Null,
});
export const Occasion = IDL.Variant({
  'wedding' : IDL.Null,
  'casual' : IDL.Null,
  'party' : IDL.Null,
  'formal' : IDL.Null,
});
export const Dress = IDL.Record({
  'id' : DressId,
  'status' : DressStatus,
  'rotationCity' : City,
  'originalPrice' : IDL.Nat,
  'priorityFees' : IDL.Vec(IDL.Nat),
  'color' : IDL.Text,
  'size' : Size,
  'productLink' : IDL.Opt(IDL.Text),
  'occasion' : Occasion,
  'brand' : IDL.Text,
  'slotsFilled' : IDL.Nat,
  'initiatorId' : UserId,
  'groupSize' : IDL.Nat,
  'authenticityProof' : ExternalBlob,
  'photos' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'city' : City,
  'name' : IDL.Text,
  'profilePhoto' : IDL.Opt(ExternalBlob),
  'trustScore' : IDL.Float64,
  'earnings' : IDL.Nat,
  'measurements' : IDL.Record({
    'hip' : IDL.Nat,
    'bust' : IDL.Nat,
    'waist' : IDL.Nat,
  }),
  'depositBalance' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const FindDressParams = IDL.Record({
  'city' : IDL.Text,
  'size' : IDL.Text,
  'priceRange' : IDL.Text,
  'searchTerm' : IDL.Text,
  'occasion' : IDL.Text,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createGroupWithDress' : IDL.Func([Group], [IDL.Text], []),
  'getAllDresses' : IDL.Func([], [IDL.Vec(Dress)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDress' : IDL.Func([DressId], [Dress], ['query']),
  'getFullGroupDetails' : IDL.Func([GroupId], [Group], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'postDressPhotos' : IDL.Func(
      [IDL.Vec(ExternalBlob), IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDresses' : IDL.Func([FindDressParams], [IDL.Vec(Dress)], ['query']),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const GroupId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserId = IDL.Principal;
  const SlotNumber = IDL.Nat;
  const GroupMember = IDL.Record({
    'slotFee' : IDL.Nat,
    'paymentStatus' : IDL.Text,
    'userId' : UserId,
    'isConfirmed' : IDL.Bool,
    'shareAmount' : IDL.Nat,
    'slotNumber' : SlotNumber,
    'depositPaid' : IDL.Bool,
  });
  const Time = IDL.Int;
  const RotationSchedule = IDL.Record({
    'status' : IDL.Text,
    'endDate' : Time,
    'userId' : UserId,
    'startDate' : Time,
  });
  const DressId = IDL.Text;
  const Group = IDL.Record({
    'id' : GroupId,
    'conditionPhotos' : IDL.Vec(ExternalBlob),
    'members' : IDL.Vec(GroupMember),
    'rotationSchedule' : IDL.Vec(RotationSchedule),
    'dressId' : DressId,
    'chatRoomId' : IDL.Text,
    'currentHolder' : IDL.Opt(UserId),
    'currentStatus' : IDL.Text,
    'handOverPhotos' : IDL.Vec(ExternalBlob),
  });
  const DressStatus = IDL.Variant({
    'resale' : IDL.Null,
    'active' : IDL.Null,
    'cleaning' : IDL.Null,
    'complete' : IDL.Null,
    'forming' : IDL.Null,
  });
  const City = IDL.Text;
  const Size = IDL.Variant({
    'L' : IDL.Null,
    'M' : IDL.Null,
    'S' : IDL.Null,
    'XL' : IDL.Null,
    'XS' : IDL.Null,
  });
  const Occasion = IDL.Variant({
    'wedding' : IDL.Null,
    'casual' : IDL.Null,
    'party' : IDL.Null,
    'formal' : IDL.Null,
  });
  const Dress = IDL.Record({
    'id' : DressId,
    'status' : DressStatus,
    'rotationCity' : City,
    'originalPrice' : IDL.Nat,
    'priorityFees' : IDL.Vec(IDL.Nat),
    'color' : IDL.Text,
    'size' : Size,
    'productLink' : IDL.Opt(IDL.Text),
    'occasion' : Occasion,
    'brand' : IDL.Text,
    'slotsFilled' : IDL.Nat,
    'initiatorId' : UserId,
    'groupSize' : IDL.Nat,
    'authenticityProof' : ExternalBlob,
    'photos' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'city' : City,
    'name' : IDL.Text,
    'profilePhoto' : IDL.Opt(ExternalBlob),
    'trustScore' : IDL.Float64,
    'earnings' : IDL.Nat,
    'measurements' : IDL.Record({
      'hip' : IDL.Nat,
      'bust' : IDL.Nat,
      'waist' : IDL.Nat,
    }),
    'depositBalance' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const FindDressParams = IDL.Record({
    'city' : IDL.Text,
    'size' : IDL.Text,
    'priceRange' : IDL.Text,
    'searchTerm' : IDL.Text,
    'occasion' : IDL.Text,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createGroupWithDress' : IDL.Func([Group], [IDL.Text], []),
    'getAllDresses' : IDL.Func([], [IDL.Vec(Dress)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDress' : IDL.Func([DressId], [Dress], ['query']),
    'getFullGroupDetails' : IDL.Func([GroupId], [Group], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'postDressPhotos' : IDL.Func(
        [IDL.Vec(ExternalBlob), IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDresses' : IDL.Func([FindDressParams], [IDL.Vec(Dress)], ['query']),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };